package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacTRichiesta {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.rich_id
	 * @mbg.generated
	 */
	private Integer richId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.id_ente
	 * @mbg.generated
	 */
	private Integer idEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.rich_periodo_da
	 * @mbg.generated
	 */
	private Date richPeriodoDa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.rich_periodo_a
	 * @mbg.generated
	 */
	private Date richPeriodoA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.rich_data
	 * @mbg.generated
	 */
	private Date richData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.rich_note
	 * @mbg.generated
	 */
	private String richNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.rich_id
	 * @return  the value of covidac_t_richiesta.rich_id
	 * @mbg.generated
	 */
	public Integer getRichId() {
		return richId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.rich_id
	 * @param richId  the value for covidac_t_richiesta.rich_id
	 * @mbg.generated
	 */
	public void setRichId(Integer richId) {
		this.richId = richId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.id_ente
	 * @return  the value of covidac_t_richiesta.id_ente
	 * @mbg.generated
	 */
	public Integer getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.id_ente
	 * @param idEnte  the value for covidac_t_richiesta.id_ente
	 * @mbg.generated
	 */
	public void setIdEnte(Integer idEnte) {
		this.idEnte = idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.rich_periodo_da
	 * @return  the value of covidac_t_richiesta.rich_periodo_da
	 * @mbg.generated
	 */
	public Date getRichPeriodoDa() {
		return richPeriodoDa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.rich_periodo_da
	 * @param richPeriodoDa  the value for covidac_t_richiesta.rich_periodo_da
	 * @mbg.generated
	 */
	public void setRichPeriodoDa(Date richPeriodoDa) {
		this.richPeriodoDa = richPeriodoDa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.rich_periodo_a
	 * @return  the value of covidac_t_richiesta.rich_periodo_a
	 * @mbg.generated
	 */
	public Date getRichPeriodoA() {
		return richPeriodoA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.rich_periodo_a
	 * @param richPeriodoA  the value for covidac_t_richiesta.rich_periodo_a
	 * @mbg.generated
	 */
	public void setRichPeriodoA(Date richPeriodoA) {
		this.richPeriodoA = richPeriodoA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.rich_data
	 * @return  the value of covidac_t_richiesta.rich_data
	 * @mbg.generated
	 */
	public Date getRichData() {
		return richData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.rich_data
	 * @param richData  the value for covidac_t_richiesta.rich_data
	 * @mbg.generated
	 */
	public void setRichData(Date richData) {
		this.richData = richData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.rich_note
	 * @return  the value of covidac_t_richiesta.rich_note
	 * @mbg.generated
	 */
	public String getRichNote() {
		return richNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.rich_note
	 * @param richNote  the value for covidac_t_richiesta.rich_note
	 * @mbg.generated
	 */
	public void setRichNote(String richNote) {
		this.richNote = richNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.data_creazione
	 * @return  the value of covidac_t_richiesta.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.data_creazione
	 * @param dataCreazione  the value for covidac_t_richiesta.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.data_modifica
	 * @return  the value of covidac_t_richiesta.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.data_modifica
	 * @param dataModifica  the value for covidac_t_richiesta.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.data_cancellazione
	 * @return  the value of covidac_t_richiesta.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.data_cancellazione
	 * @param dataCancellazione  the value for covidac_t_richiesta.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta.utente_operazione
	 * @return  the value of covidac_t_richiesta.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta.utente_operazione
	 * @param utenteOperazione  the value for covidac_t_richiesta.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}