package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacROrdineStato {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.ordrstato_id
	 * @mbg.generated
	 */
	private Integer ordrstatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.ord_id
	 * @mbg.generated
	 */
	private Integer ordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.ord_stato_id
	 * @mbg.generated
	 */
	private Integer ordStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.data_consegna
	 * @mbg.generated
	 */
	private Date dataConsegna;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_stato.quantita_consegnata
	 * @mbg.generated
	 */
	private Integer quantitaConsegnata;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.ordrstato_id
	 * @return  the value of covidac_r_ordine_stato.ordrstato_id
	 * @mbg.generated
	 */
	public Integer getOrdrstatoId() {
		return ordrstatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.ordrstato_id
	 * @param ordrstatoId  the value for covidac_r_ordine_stato.ordrstato_id
	 * @mbg.generated
	 */
	public void setOrdrstatoId(Integer ordrstatoId) {
		this.ordrstatoId = ordrstatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.ord_id
	 * @return  the value of covidac_r_ordine_stato.ord_id
	 * @mbg.generated
	 */
	public Integer getOrdId() {
		return ordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.ord_id
	 * @param ordId  the value for covidac_r_ordine_stato.ord_id
	 * @mbg.generated
	 */
	public void setOrdId(Integer ordId) {
		this.ordId = ordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.ord_stato_id
	 * @return  the value of covidac_r_ordine_stato.ord_stato_id
	 * @mbg.generated
	 */
	public Integer getOrdStatoId() {
		return ordStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.ord_stato_id
	 * @param ordStatoId  the value for covidac_r_ordine_stato.ord_stato_id
	 * @mbg.generated
	 */
	public void setOrdStatoId(Integer ordStatoId) {
		this.ordStatoId = ordStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.validita_inizio
	 * @return  the value of covidac_r_ordine_stato.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.validita_inizio
	 * @param validitaInizio  the value for covidac_r_ordine_stato.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.validita_fine
	 * @return  the value of covidac_r_ordine_stato.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.validita_fine
	 * @param validitaFine  the value for covidac_r_ordine_stato.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.data_creazione
	 * @return  the value of covidac_r_ordine_stato.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.data_creazione
	 * @param dataCreazione  the value for covidac_r_ordine_stato.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.data_modifica
	 * @return  the value of covidac_r_ordine_stato.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.data_modifica
	 * @param dataModifica  the value for covidac_r_ordine_stato.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.data_cancellazione
	 * @return  the value of covidac_r_ordine_stato.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.data_cancellazione
	 * @param dataCancellazione  the value for covidac_r_ordine_stato.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.utente_operazione
	 * @return  the value of covidac_r_ordine_stato.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.utente_operazione
	 * @param utenteOperazione  the value for covidac_r_ordine_stato.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.data_consegna
	 * @return  the value of covidac_r_ordine_stato.data_consegna
	 * @mbg.generated
	 */
	public Date getDataConsegna() {
		return dataConsegna;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.data_consegna
	 * @param dataConsegna  the value for covidac_r_ordine_stato.data_consegna
	 * @mbg.generated
	 */
	public void setDataConsegna(Date dataConsegna) {
		this.dataConsegna = dataConsegna;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_stato.quantita_consegnata
	 * @return  the value of covidac_r_ordine_stato.quantita_consegnata
	 * @mbg.generated
	 */
	public Integer getQuantitaConsegnata() {
		return quantitaConsegnata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_stato.quantita_consegnata
	 * @param quantitaConsegnata  the value for covidac_r_ordine_stato.quantita_consegnata
	 * @mbg.generated
	 */
	public void setQuantitaConsegnata(Integer quantitaConsegnata) {
		this.quantitaConsegnata = quantitaConsegnata;
	}
}