package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacROrdineRicDet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.ricdet_stato_id
	 * @mbg.generated
	 */
	private Integer ricdetStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.ord_id
	 * @mbg.generated
	 */
	private Integer ordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.ricdet_id
	 * @mbg.generated
	 */
	private Integer ricdetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_ordine_ric_det.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.ricdet_stato_id
	 * @return  the value of covidac_r_ordine_ric_det.ricdet_stato_id
	 * @mbg.generated
	 */
	public Integer getRicdetStatoId() {
		return ricdetStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.ricdet_stato_id
	 * @param ricdetStatoId  the value for covidac_r_ordine_ric_det.ricdet_stato_id
	 * @mbg.generated
	 */
	public void setRicdetStatoId(Integer ricdetStatoId) {
		this.ricdetStatoId = ricdetStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.ord_id
	 * @return  the value of covidac_r_ordine_ric_det.ord_id
	 * @mbg.generated
	 */
	public Integer getOrdId() {
		return ordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.ord_id
	 * @param ordId  the value for covidac_r_ordine_ric_det.ord_id
	 * @mbg.generated
	 */
	public void setOrdId(Integer ordId) {
		this.ordId = ordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.ricdet_id
	 * @return  the value of covidac_r_ordine_ric_det.ricdet_id
	 * @mbg.generated
	 */
	public Integer getRicdetId() {
		return ricdetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.ricdet_id
	 * @param ricdetId  the value for covidac_r_ordine_ric_det.ricdet_id
	 * @mbg.generated
	 */
	public void setRicdetId(Integer ricdetId) {
		this.ricdetId = ricdetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.data_creazione
	 * @return  the value of covidac_r_ordine_ric_det.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.data_creazione
	 * @param dataCreazione  the value for covidac_r_ordine_ric_det.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.data_modifica
	 * @return  the value of covidac_r_ordine_ric_det.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.data_modifica
	 * @param dataModifica  the value for covidac_r_ordine_ric_det.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.data_cancellazione
	 * @return  the value of covidac_r_ordine_ric_det.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.data_cancellazione
	 * @param dataCancellazione  the value for covidac_r_ordine_ric_det.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_ordine_ric_det.utente_operazione
	 * @return  the value of covidac_r_ordine_ric_det.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_ordine_ric_det.utente_operazione
	 * @param utenteOperazione  the value for covidac_r_ordine_ric_det.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}