package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacTOrdine {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.ord_id
	 * @mbg.generated
	 */
	private Integer ordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.ord_identificativo
	 * @mbg.generated
	 */
	private String ordIdentificativo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.ord_data
	 * @mbg.generated
	 */
	private Date ordData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.ord_data_consegna_prevista
	 * @mbg.generated
	 */
	private Date ordDataConsegnaPrevista;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.ord_data_consegna
	 * @mbg.generated
	 */
	private Date ordDataConsegna;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.prod_id
	 * @mbg.generated
	 */
	private Integer prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.quantita_ordinata
	 * @mbg.generated
	 */
	private Integer quantitaOrdinata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.quantita_consegnata
	 * @mbg.generated
	 */
	private Integer quantitaConsegnata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_ordine.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.ord_id
	 * @return  the value of covidac_t_ordine.ord_id
	 * @mbg.generated
	 */
	public Integer getOrdId() {
		return ordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.ord_id
	 * @param ordId  the value for covidac_t_ordine.ord_id
	 * @mbg.generated
	 */
	public void setOrdId(Integer ordId) {
		this.ordId = ordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.ord_identificativo
	 * @return  the value of covidac_t_ordine.ord_identificativo
	 * @mbg.generated
	 */
	public String getOrdIdentificativo() {
		return ordIdentificativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.ord_identificativo
	 * @param ordIdentificativo  the value for covidac_t_ordine.ord_identificativo
	 * @mbg.generated
	 */
	public void setOrdIdentificativo(String ordIdentificativo) {
		this.ordIdentificativo = ordIdentificativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.ord_data
	 * @return  the value of covidac_t_ordine.ord_data
	 * @mbg.generated
	 */
	public Date getOrdData() {
		return ordData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.ord_data
	 * @param ordData  the value for covidac_t_ordine.ord_data
	 * @mbg.generated
	 */
	public void setOrdData(Date ordData) {
		this.ordData = ordData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.ord_data_consegna_prevista
	 * @return  the value of covidac_t_ordine.ord_data_consegna_prevista
	 * @mbg.generated
	 */
	public Date getOrdDataConsegnaPrevista() {
		return ordDataConsegnaPrevista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.ord_data_consegna_prevista
	 * @param ordDataConsegnaPrevista  the value for covidac_t_ordine.ord_data_consegna_prevista
	 * @mbg.generated
	 */
	public void setOrdDataConsegnaPrevista(Date ordDataConsegnaPrevista) {
		this.ordDataConsegnaPrevista = ordDataConsegnaPrevista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.ord_data_consegna
	 * @return  the value of covidac_t_ordine.ord_data_consegna
	 * @mbg.generated
	 */
	public Date getOrdDataConsegna() {
		return ordDataConsegna;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.ord_data_consegna
	 * @param ordDataConsegna  the value for covidac_t_ordine.ord_data_consegna
	 * @mbg.generated
	 */
	public void setOrdDataConsegna(Date ordDataConsegna) {
		this.ordDataConsegna = ordDataConsegna;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.prod_id
	 * @return  the value of covidac_t_ordine.prod_id
	 * @mbg.generated
	 */
	public Integer getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.prod_id
	 * @param prodId  the value for covidac_t_ordine.prod_id
	 * @mbg.generated
	 */
	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.quantita_ordinata
	 * @return  the value of covidac_t_ordine.quantita_ordinata
	 * @mbg.generated
	 */
	public Integer getQuantitaOrdinata() {
		return quantitaOrdinata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.quantita_ordinata
	 * @param quantitaOrdinata  the value for covidac_t_ordine.quantita_ordinata
	 * @mbg.generated
	 */
	public void setQuantitaOrdinata(Integer quantitaOrdinata) {
		this.quantitaOrdinata = quantitaOrdinata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.quantita_consegnata
	 * @return  the value of covidac_t_ordine.quantita_consegnata
	 * @mbg.generated
	 */
	public Integer getQuantitaConsegnata() {
		return quantitaConsegnata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.quantita_consegnata
	 * @param quantitaConsegnata  the value for covidac_t_ordine.quantita_consegnata
	 * @mbg.generated
	 */
	public void setQuantitaConsegnata(Integer quantitaConsegnata) {
		this.quantitaConsegnata = quantitaConsegnata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.data_creazione
	 * @return  the value of covidac_t_ordine.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.data_creazione
	 * @param dataCreazione  the value for covidac_t_ordine.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.data_modifica
	 * @return  the value of covidac_t_ordine.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.data_modifica
	 * @param dataModifica  the value for covidac_t_ordine.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.data_cancellazione
	 * @return  the value of covidac_t_ordine.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.data_cancellazione
	 * @param dataCancellazione  the value for covidac_t_ordine.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_ordine.utente_operazione
	 * @return  the value of covidac_t_ordine.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_ordine.utente_operazione
	 * @param utenteOperazione  the value for covidac_t_ordine.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}