package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacTRichiestaDet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.ricdet_id
	 * @mbg.generated
	 */
	private Integer ricdetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.rich_id
	 * @mbg.generated
	 */
	private Integer richId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.prod_id
	 * @mbg.generated
	 */
	private Integer prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.quantita
	 * @mbg.generated
	 */
	private Integer quantita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.fabbisogno_giornaliero
	 * @mbg.generated
	 */
	private Integer fabbisognoGiornaliero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.fabbisogno_settimanale
	 * @mbg.generated
	 */
	private Integer fabbisognoSettimanale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.dotazione_attuale
	 * @mbg.generated
	 */
	private Integer dotazioneAttuale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_richiesta_det.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.ricdet_id
	 * @return  the value of covidac_t_richiesta_det.ricdet_id
	 * @mbg.generated
	 */
	public Integer getRicdetId() {
		return ricdetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.ricdet_id
	 * @param ricdetId  the value for covidac_t_richiesta_det.ricdet_id
	 * @mbg.generated
	 */
	public void setRicdetId(Integer ricdetId) {
		this.ricdetId = ricdetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.rich_id
	 * @return  the value of covidac_t_richiesta_det.rich_id
	 * @mbg.generated
	 */
	public Integer getRichId() {
		return richId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.rich_id
	 * @param richId  the value for covidac_t_richiesta_det.rich_id
	 * @mbg.generated
	 */
	public void setRichId(Integer richId) {
		this.richId = richId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.prod_id
	 * @return  the value of covidac_t_richiesta_det.prod_id
	 * @mbg.generated
	 */
	public Integer getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.prod_id
	 * @param prodId  the value for covidac_t_richiesta_det.prod_id
	 * @mbg.generated
	 */
	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.quantita
	 * @return  the value of covidac_t_richiesta_det.quantita
	 * @mbg.generated
	 */
	public Integer getQuantita() {
		return quantita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.quantita
	 * @param quantita  the value for covidac_t_richiesta_det.quantita
	 * @mbg.generated
	 */
	public void setQuantita(Integer quantita) {
		this.quantita = quantita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.fabbisogno_giornaliero
	 * @return  the value of covidac_t_richiesta_det.fabbisogno_giornaliero
	 * @mbg.generated
	 */
	public Integer getFabbisognoGiornaliero() {
		return fabbisognoGiornaliero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.fabbisogno_giornaliero
	 * @param fabbisognoGiornaliero  the value for covidac_t_richiesta_det.fabbisogno_giornaliero
	 * @mbg.generated
	 */
	public void setFabbisognoGiornaliero(Integer fabbisognoGiornaliero) {
		this.fabbisognoGiornaliero = fabbisognoGiornaliero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.fabbisogno_settimanale
	 * @return  the value of covidac_t_richiesta_det.fabbisogno_settimanale
	 * @mbg.generated
	 */
	public Integer getFabbisognoSettimanale() {
		return fabbisognoSettimanale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.fabbisogno_settimanale
	 * @param fabbisognoSettimanale  the value for covidac_t_richiesta_det.fabbisogno_settimanale
	 * @mbg.generated
	 */
	public void setFabbisognoSettimanale(Integer fabbisognoSettimanale) {
		this.fabbisognoSettimanale = fabbisognoSettimanale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.dotazione_attuale
	 * @return  the value of covidac_t_richiesta_det.dotazione_attuale
	 * @mbg.generated
	 */
	public Integer getDotazioneAttuale() {
		return dotazioneAttuale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.dotazione_attuale
	 * @param dotazioneAttuale  the value for covidac_t_richiesta_det.dotazione_attuale
	 * @mbg.generated
	 */
	public void setDotazioneAttuale(Integer dotazioneAttuale) {
		this.dotazioneAttuale = dotazioneAttuale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.data_creazione
	 * @return  the value of covidac_t_richiesta_det.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.data_creazione
	 * @param dataCreazione  the value for covidac_t_richiesta_det.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.data_modifica
	 * @return  the value of covidac_t_richiesta_det.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.data_modifica
	 * @param dataModifica  the value for covidac_t_richiesta_det.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.data_cancellazione
	 * @return  the value of covidac_t_richiesta_det.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.data_cancellazione
	 * @param dataCancellazione  the value for covidac_t_richiesta_det.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.utente_operazione
	 * @return  the value of covidac_t_richiesta_det.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.utente_operazione
	 * @param utenteOperazione  the value for covidac_t_richiesta_det.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_richiesta_det.id_struttura
	 * @return  the value of covidac_t_richiesta_det.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_richiesta_det.id_struttura
	 * @param idStruttura  the value for covidac_t_richiesta_det.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}
}