package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacRMagazProd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.prodmag_id
	 * @mbg.generated
	 */
	private Integer prodmagId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.magaz_id
	 * @mbg.generated
	 */
	private Integer magazId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.prod_id
	 * @mbg.generated
	 */
	private Integer prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.quantita_disponibile
	 * @mbg.generated
	 */
	private Integer quantitaDisponibile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.quantita_distribuita
	 * @mbg.generated
	 */
	private Integer quantitaDistribuita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_r_magaz_prod.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.prodmag_id
	 * @return  the value of covidac_r_magaz_prod.prodmag_id
	 * @mbg.generated
	 */
	public Integer getProdmagId() {
		return prodmagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.prodmag_id
	 * @param prodmagId  the value for covidac_r_magaz_prod.prodmag_id
	 * @mbg.generated
	 */
	public void setProdmagId(Integer prodmagId) {
		this.prodmagId = prodmagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.magaz_id
	 * @return  the value of covidac_r_magaz_prod.magaz_id
	 * @mbg.generated
	 */
	public Integer getMagazId() {
		return magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.magaz_id
	 * @param magazId  the value for covidac_r_magaz_prod.magaz_id
	 * @mbg.generated
	 */
	public void setMagazId(Integer magazId) {
		this.magazId = magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.prod_id
	 * @return  the value of covidac_r_magaz_prod.prod_id
	 * @mbg.generated
	 */
	public Integer getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.prod_id
	 * @param prodId  the value for covidac_r_magaz_prod.prod_id
	 * @mbg.generated
	 */
	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.quantita_disponibile
	 * @return  the value of covidac_r_magaz_prod.quantita_disponibile
	 * @mbg.generated
	 */
	public Integer getQuantitaDisponibile() {
		return quantitaDisponibile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.quantita_disponibile
	 * @param quantitaDisponibile  the value for covidac_r_magaz_prod.quantita_disponibile
	 * @mbg.generated
	 */
	public void setQuantitaDisponibile(Integer quantitaDisponibile) {
		this.quantitaDisponibile = quantitaDisponibile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.quantita_distribuita
	 * @return  the value of covidac_r_magaz_prod.quantita_distribuita
	 * @mbg.generated
	 */
	public Integer getQuantitaDistribuita() {
		return quantitaDistribuita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.quantita_distribuita
	 * @param quantitaDistribuita  the value for covidac_r_magaz_prod.quantita_distribuita
	 * @mbg.generated
	 */
	public void setQuantitaDistribuita(Integer quantitaDistribuita) {
		this.quantitaDistribuita = quantitaDistribuita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.validita_inizio
	 * @return  the value of covidac_r_magaz_prod.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.validita_inizio
	 * @param validitaInizio  the value for covidac_r_magaz_prod.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.validita_fine
	 * @return  the value of covidac_r_magaz_prod.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.validita_fine
	 * @param validitaFine  the value for covidac_r_magaz_prod.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.data_creazione
	 * @return  the value of covidac_r_magaz_prod.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.data_creazione
	 * @param dataCreazione  the value for covidac_r_magaz_prod.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.data_modifica
	 * @return  the value of covidac_r_magaz_prod.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.data_modifica
	 * @param dataModifica  the value for covidac_r_magaz_prod.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.data_cancellazione
	 * @return  the value of covidac_r_magaz_prod.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.data_cancellazione
	 * @param dataCancellazione  the value for covidac_r_magaz_prod.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_r_magaz_prod.utente_operazione
	 * @return  the value of covidac_r_magaz_prod.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_r_magaz_prod.utente_operazione
	 * @param utenteOperazione  the value for covidac_r_magaz_prod.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}