package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.math.BigDecimal;
import java.util.Date;

public class CovidacCPercDist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.pd_id
	 * @mbg.generated
	 */
	private Integer pdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.id_ente
	 * @mbg.generated
	 */
	private Integer idEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.pd_percentuale_distribuzione
	 * @mbg.generated
	 */
	private BigDecimal pdPercentualeDistribuzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.pd_algoritmo_distribuzione
	 * @mbg.generated
	 */
	private String pdAlgoritmoDistribuzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_c_perc_dist.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.pd_id
	 * @return  the value of covidac_c_perc_dist.pd_id
	 * @mbg.generated
	 */
	public Integer getPdId() {
		return pdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.pd_id
	 * @param pdId  the value for covidac_c_perc_dist.pd_id
	 * @mbg.generated
	 */
	public void setPdId(Integer pdId) {
		this.pdId = pdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.id_ente
	 * @return  the value of covidac_c_perc_dist.id_ente
	 * @mbg.generated
	 */
	public Integer getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.id_ente
	 * @param idEnte  the value for covidac_c_perc_dist.id_ente
	 * @mbg.generated
	 */
	public void setIdEnte(Integer idEnte) {
		this.idEnte = idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.pd_percentuale_distribuzione
	 * @return  the value of covidac_c_perc_dist.pd_percentuale_distribuzione
	 * @mbg.generated
	 */
	public BigDecimal getPdPercentualeDistribuzione() {
		return pdPercentualeDistribuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.pd_percentuale_distribuzione
	 * @param pdPercentualeDistribuzione  the value for covidac_c_perc_dist.pd_percentuale_distribuzione
	 * @mbg.generated
	 */
	public void setPdPercentualeDistribuzione(BigDecimal pdPercentualeDistribuzione) {
		this.pdPercentualeDistribuzione = pdPercentualeDistribuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.pd_algoritmo_distribuzione
	 * @return  the value of covidac_c_perc_dist.pd_algoritmo_distribuzione
	 * @mbg.generated
	 */
	public String getPdAlgoritmoDistribuzione() {
		return pdAlgoritmoDistribuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.pd_algoritmo_distribuzione
	 * @param pdAlgoritmoDistribuzione  the value for covidac_c_perc_dist.pd_algoritmo_distribuzione
	 * @mbg.generated
	 */
	public void setPdAlgoritmoDistribuzione(String pdAlgoritmoDistribuzione) {
		this.pdAlgoritmoDistribuzione = pdAlgoritmoDistribuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.validita_inizio
	 * @return  the value of covidac_c_perc_dist.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.validita_inizio
	 * @param validitaInizio  the value for covidac_c_perc_dist.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.validita_fine
	 * @return  the value of covidac_c_perc_dist.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.validita_fine
	 * @param validitaFine  the value for covidac_c_perc_dist.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.data_creazione
	 * @return  the value of covidac_c_perc_dist.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.data_creazione
	 * @param dataCreazione  the value for covidac_c_perc_dist.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.data_modifica
	 * @return  the value of covidac_c_perc_dist.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.data_modifica
	 * @param dataModifica  the value for covidac_c_perc_dist.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.data_cancellazione
	 * @return  the value of covidac_c_perc_dist.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.data_cancellazione
	 * @param dataCancellazione  the value for covidac_c_perc_dist.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.utente_operazione
	 * @return  the value of covidac_c_perc_dist.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.utente_operazione
	 * @param utenteOperazione  the value for covidac_c_perc_dist.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_c_perc_dist.id_struttura
	 * @return  the value of covidac_c_perc_dist.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_c_perc_dist.id_struttura
	 * @param idStruttura  the value for covidac_c_perc_dist.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}
}