package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacDRichiestaStato {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.ric_stato_id
	 * @mbg.generated
	 */
	private Integer ricStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.ric_stato_cod
	 * @mbg.generated
	 */
	private String ricStatoCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.ric_stato_desc
	 * @mbg.generated
	 */
	private String ricStatoDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_d_richiesta_stato.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.ric_stato_id
	 * @return  the value of covidac_d_richiesta_stato.ric_stato_id
	 * @mbg.generated
	 */
	public Integer getRicStatoId() {
		return ricStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.ric_stato_id
	 * @param ricStatoId  the value for covidac_d_richiesta_stato.ric_stato_id
	 * @mbg.generated
	 */
	public void setRicStatoId(Integer ricStatoId) {
		this.ricStatoId = ricStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.ric_stato_cod
	 * @return  the value of covidac_d_richiesta_stato.ric_stato_cod
	 * @mbg.generated
	 */
	public String getRicStatoCod() {
		return ricStatoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.ric_stato_cod
	 * @param ricStatoCod  the value for covidac_d_richiesta_stato.ric_stato_cod
	 * @mbg.generated
	 */
	public void setRicStatoCod(String ricStatoCod) {
		this.ricStatoCod = ricStatoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.ric_stato_desc
	 * @return  the value of covidac_d_richiesta_stato.ric_stato_desc
	 * @mbg.generated
	 */
	public String getRicStatoDesc() {
		return ricStatoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.ric_stato_desc
	 * @param ricStatoDesc  the value for covidac_d_richiesta_stato.ric_stato_desc
	 * @mbg.generated
	 */
	public void setRicStatoDesc(String ricStatoDesc) {
		this.ricStatoDesc = ricStatoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.validita_inizio
	 * @return  the value of covidac_d_richiesta_stato.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.validita_inizio
	 * @param validitaInizio  the value for covidac_d_richiesta_stato.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.validita_fine
	 * @return  the value of covidac_d_richiesta_stato.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.validita_fine
	 * @param validitaFine  the value for covidac_d_richiesta_stato.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.data_creazione
	 * @return  the value of covidac_d_richiesta_stato.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.data_creazione
	 * @param dataCreazione  the value for covidac_d_richiesta_stato.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.data_modifica
	 * @return  the value of covidac_d_richiesta_stato.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.data_modifica
	 * @param dataModifica  the value for covidac_d_richiesta_stato.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.data_cancellazione
	 * @return  the value of covidac_d_richiesta_stato.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.data_cancellazione
	 * @param dataCancellazione  the value for covidac_d_richiesta_stato.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_d_richiesta_stato.utente_operazione
	 * @return  the value of covidac_d_richiesta_stato.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_d_richiesta_stato.utente_operazione
	 * @param utenteOperazione  the value for covidac_d_richiesta_stato.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}