package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacTMagazzino {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.magaz_id
	 * @mbg.generated
	 */
	private Integer magazId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.magaz_nome
	 * @mbg.generated
	 */
	private String magazNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.magaz_indirizzo
	 * @mbg.generated
	 */
	private String magazIndirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.magaz_comune_codice
	 * @mbg.generated
	 */
	private String magazComuneCodice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magazzino.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.magaz_id
	 * @return  the value of covidac_t_magazzino.magaz_id
	 * @mbg.generated
	 */
	public Integer getMagazId() {
		return magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.magaz_id
	 * @param magazId  the value for covidac_t_magazzino.magaz_id
	 * @mbg.generated
	 */
	public void setMagazId(Integer magazId) {
		this.magazId = magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.magaz_nome
	 * @return  the value of covidac_t_magazzino.magaz_nome
	 * @mbg.generated
	 */
	public String getMagazNome() {
		return magazNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.magaz_nome
	 * @param magazNome  the value for covidac_t_magazzino.magaz_nome
	 * @mbg.generated
	 */
	public void setMagazNome(String magazNome) {
		this.magazNome = magazNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.magaz_indirizzo
	 * @return  the value of covidac_t_magazzino.magaz_indirizzo
	 * @mbg.generated
	 */
	public String getMagazIndirizzo() {
		return magazIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.magaz_indirizzo
	 * @param magazIndirizzo  the value for covidac_t_magazzino.magaz_indirizzo
	 * @mbg.generated
	 */
	public void setMagazIndirizzo(String magazIndirizzo) {
		this.magazIndirizzo = magazIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.magaz_comune_codice
	 * @return  the value of covidac_t_magazzino.magaz_comune_codice
	 * @mbg.generated
	 */
	public String getMagazComuneCodice() {
		return magazComuneCodice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.magaz_comune_codice
	 * @param magazComuneCodice  the value for covidac_t_magazzino.magaz_comune_codice
	 * @mbg.generated
	 */
	public void setMagazComuneCodice(String magazComuneCodice) {
		this.magazComuneCodice = magazComuneCodice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.validita_inizio
	 * @return  the value of covidac_t_magazzino.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.validita_inizio
	 * @param validitaInizio  the value for covidac_t_magazzino.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.validita_fine
	 * @return  the value of covidac_t_magazzino.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.validita_fine
	 * @param validitaFine  the value for covidac_t_magazzino.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.data_creazione
	 * @return  the value of covidac_t_magazzino.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.data_creazione
	 * @param dataCreazione  the value for covidac_t_magazzino.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.data_modifica
	 * @return  the value of covidac_t_magazzino.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.data_modifica
	 * @param dataModifica  the value for covidac_t_magazzino.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.data_cancellazione
	 * @return  the value of covidac_t_magazzino.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.data_cancellazione
	 * @param dataCancellazione  the value for covidac_t_magazzino.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magazzino.utente_operazione
	 * @return  the value of covidac_t_magazzino.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magazzino.utente_operazione
	 * @param utenteOperazione  the value for covidac_t_magazzino.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}