package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacTMagazUscita {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.magu_id
	 * @mbg.generated
	 */
	private Integer maguId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.magaz_id
	 * @mbg.generated
	 */
	private Integer magazId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.id_ente
	 * @mbg.generated
	 */
	private Integer idEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.prod_id
	 * @mbg.generated
	 */
	private Integer prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.quantita
	 * @mbg.generated
	 */
	private Integer quantita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.data_registrazione
	 * @mbg.generated
	 */
	private Date dataRegistrazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.data_consegna
	 * @mbg.generated
	 */
	private Date dataConsegna;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_uscita.quantita_distribuibile
	 * @mbg.generated
	 */
	private Integer quantitaDistribuibile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.magu_id
	 * @return  the value of covidac_t_magaz_uscita.magu_id
	 * @mbg.generated
	 */
	public Integer getMaguId() {
		return maguId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.magu_id
	 * @param maguId  the value for covidac_t_magaz_uscita.magu_id
	 * @mbg.generated
	 */
	public void setMaguId(Integer maguId) {
		this.maguId = maguId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.magaz_id
	 * @return  the value of covidac_t_magaz_uscita.magaz_id
	 * @mbg.generated
	 */
	public Integer getMagazId() {
		return magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.magaz_id
	 * @param magazId  the value for covidac_t_magaz_uscita.magaz_id
	 * @mbg.generated
	 */
	public void setMagazId(Integer magazId) {
		this.magazId = magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.id_ente
	 * @return  the value of covidac_t_magaz_uscita.id_ente
	 * @mbg.generated
	 */
	public Integer getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.id_ente
	 * @param idEnte  the value for covidac_t_magaz_uscita.id_ente
	 * @mbg.generated
	 */
	public void setIdEnte(Integer idEnte) {
		this.idEnte = idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.prod_id
	 * @return  the value of covidac_t_magaz_uscita.prod_id
	 * @mbg.generated
	 */
	public Integer getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.prod_id
	 * @param prodId  the value for covidac_t_magaz_uscita.prod_id
	 * @mbg.generated
	 */
	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.quantita
	 * @return  the value of covidac_t_magaz_uscita.quantita
	 * @mbg.generated
	 */
	public Integer getQuantita() {
		return quantita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.quantita
	 * @param quantita  the value for covidac_t_magaz_uscita.quantita
	 * @mbg.generated
	 */
	public void setQuantita(Integer quantita) {
		this.quantita = quantita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.data_registrazione
	 * @return  the value of covidac_t_magaz_uscita.data_registrazione
	 * @mbg.generated
	 */
	public Date getDataRegistrazione() {
		return dataRegistrazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.data_registrazione
	 * @param dataRegistrazione  the value for covidac_t_magaz_uscita.data_registrazione
	 * @mbg.generated
	 */
	public void setDataRegistrazione(Date dataRegistrazione) {
		this.dataRegistrazione = dataRegistrazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.data_consegna
	 * @return  the value of covidac_t_magaz_uscita.data_consegna
	 * @mbg.generated
	 */
	public Date getDataConsegna() {
		return dataConsegna;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.data_consegna
	 * @param dataConsegna  the value for covidac_t_magaz_uscita.data_consegna
	 * @mbg.generated
	 */
	public void setDataConsegna(Date dataConsegna) {
		this.dataConsegna = dataConsegna;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.data_creazione
	 * @return  the value of covidac_t_magaz_uscita.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.data_creazione
	 * @param dataCreazione  the value for covidac_t_magaz_uscita.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.data_modifica
	 * @return  the value of covidac_t_magaz_uscita.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.data_modifica
	 * @param dataModifica  the value for covidac_t_magaz_uscita.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.data_cancellazione
	 * @return  the value of covidac_t_magaz_uscita.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.data_cancellazione
	 * @param dataCancellazione  the value for covidac_t_magaz_uscita.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.utente_operazione
	 * @return  the value of covidac_t_magaz_uscita.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.utente_operazione
	 * @param utenteOperazione  the value for covidac_t_magaz_uscita.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.id_struttura
	 * @return  the value of covidac_t_magaz_uscita.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.id_struttura
	 * @param idStruttura  the value for covidac_t_magaz_uscita.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_uscita.quantita_distribuibile
	 * @return  the value of covidac_t_magaz_uscita.quantita_distribuibile
	 * @mbg.generated
	 */
	public Integer getQuantitaDistribuibile() {
		return quantitaDistribuibile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_uscita.quantita_distribuibile
	 * @param quantitaDistribuibile  the value for covidac_t_magaz_uscita.quantita_distribuibile
	 * @mbg.generated
	 */
	public void setQuantitaDistribuibile(Integer quantitaDistribuibile) {
		this.quantitaDistribuibile = quantitaDistribuibile;
	}
}