package it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidacTMagazEntrata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.mage_id
	 * @mbg.generated
	 */
	private Integer mageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.magaz_id
	 * @mbg.generated
	 */
	private Integer magazId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.prod_id
	 * @mbg.generated
	 */
	private Integer prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.quantita
	 * @mbg.generated
	 */
	private Integer quantita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.data_registrazione
	 * @mbg.generated
	 */
	private Date dataRegistrazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidac_t_magaz_entrata.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.mage_id
	 * @return  the value of covidac_t_magaz_entrata.mage_id
	 * @mbg.generated
	 */
	public Integer getMageId() {
		return mageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.mage_id
	 * @param mageId  the value for covidac_t_magaz_entrata.mage_id
	 * @mbg.generated
	 */
	public void setMageId(Integer mageId) {
		this.mageId = mageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.magaz_id
	 * @return  the value of covidac_t_magaz_entrata.magaz_id
	 * @mbg.generated
	 */
	public Integer getMagazId() {
		return magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.magaz_id
	 * @param magazId  the value for covidac_t_magaz_entrata.magaz_id
	 * @mbg.generated
	 */
	public void setMagazId(Integer magazId) {
		this.magazId = magazId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.prod_id
	 * @return  the value of covidac_t_magaz_entrata.prod_id
	 * @mbg.generated
	 */
	public Integer getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.prod_id
	 * @param prodId  the value for covidac_t_magaz_entrata.prod_id
	 * @mbg.generated
	 */
	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.quantita
	 * @return  the value of covidac_t_magaz_entrata.quantita
	 * @mbg.generated
	 */
	public Integer getQuantita() {
		return quantita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.quantita
	 * @param quantita  the value for covidac_t_magaz_entrata.quantita
	 * @mbg.generated
	 */
	public void setQuantita(Integer quantita) {
		this.quantita = quantita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.data_registrazione
	 * @return  the value of covidac_t_magaz_entrata.data_registrazione
	 * @mbg.generated
	 */
	public Date getDataRegistrazione() {
		return dataRegistrazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.data_registrazione
	 * @param dataRegistrazione  the value for covidac_t_magaz_entrata.data_registrazione
	 * @mbg.generated
	 */
	public void setDataRegistrazione(Date dataRegistrazione) {
		this.dataRegistrazione = dataRegistrazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.data_creazione
	 * @return  the value of covidac_t_magaz_entrata.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.data_creazione
	 * @param dataCreazione  the value for covidac_t_magaz_entrata.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.data_modifica
	 * @return  the value of covidac_t_magaz_entrata.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.data_modifica
	 * @param dataModifica  the value for covidac_t_magaz_entrata.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.data_cancellazione
	 * @return  the value of covidac_t_magaz_entrata.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.data_cancellazione
	 * @param dataCancellazione  the value for covidac_t_magaz_entrata.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidac_t_magaz_entrata.utente_operazione
	 * @return  the value of covidac_t_magaz_entrata.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidac_t_magaz_entrata.utente_operazione
	 * @param utenteOperazione  the value for covidac_t_magaz_entrata.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}