package it.csi.gescovid.acquistiapi.business.be.impl.mapper.extended;

import java.util.List;

import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import it.csi.gescovid.acquistiapi.business.be.impl.mapper.dto.extended.richieste.SelectAllMagazzinoUscita;
import it.csi.gescovid.acquistiapi.business.be.impl.mapper.generated.BaseCovidacTRichiestaDetMapper;

public interface DistribuzioniServiceMapper extends BaseCovidacTRichiestaDetMapper {

	@Select({
	    "select",
	    "	tb.magu_id,",
	    "	tb.magaz_id,",
	    "	tb.id_ente,",
	    "	tb.quantita,",
	    "	tb.data_registrazione,",
	    "	tb.data_consegna,",
	    "	tb.data_creazione,",
	    "	tb.data_modifica,",
	    "	tb.data_cancellazione,",
	    "	tb.utente_operazione,",
	    "	tb.prod_id,",
	    "	tb.prod_cod,",
	    "	tb.prod_nome,",
	    "	tb.prod_desc,",
	    "	st.id_struttura,",
	    "	st.nome",
	    "from",
	    "	(",
	    "	select",
	    "		m.magu_id,",
	    "		m.magaz_id,",
	    "		m.id_ente,",
	    "		m.quantita,",
	    "		m.data_registrazione,",
	    "		m.data_consegna,",
	    "		m.data_creazione,",
	    "		m.data_modifica,",
	    "		m.data_cancellazione,",
	    "		m.utente_operazione,",
	    "		p.prod_id,",
	    "		p.prod_cod,",
	    "		p.prod_nome,",
	    "		p.prod_desc,",
	    "		m.id_struttura",
	    "	from",
	    "		covidac_t_prod p,",
	    "		covidac_t_magaz_uscita m",
	    "	where",
	    "		p.prod_id = m.prod_id",
	    "		and p.data_cancellazione is null",
	    "		and m.data_cancellazione is null) as tb",
	    "left join struttura st on",
	    "	tb.id_struttura = st.id_struttura"
			})
		@Results({
			@Result(column = "magu_id", property = "maguId", jdbcType = JdbcType.INTEGER),
			@Result(column = "magaz_id", property = "magazId", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_ente", property = "idEnte", jdbcType = JdbcType.INTEGER),
			@Result(column = "quantita", property = "quantita", jdbcType = JdbcType.INTEGER),
			@Result(column = "data_registrazione", property = "dataRegistrazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_consegna", property = "dataConsegna", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_creazione", property = "dataCreazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_modifica", property = "dataModifica", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_cancellazione", property = "dataCancellazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
		    @Result(column = "prod_id", property="prodId", jdbcType=JdbcType.INTEGER),
		    @Result(column = "prod_cod", property="prodCod", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_nome", property="prodNome", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_desc", property="prodDesc", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "nome", property="nome", jdbcType=JdbcType.VARCHAR)
		})
		List<SelectAllMagazzinoUscita> selectMagazzinoUscitaAll();
		
		@Select({
	    "select",
	    "	tb.magu_id,",
	    "	tb.magaz_id,",
	    "	tb.id_ente,",
	    "	tb.quantita,",
	    "	tb.data_registrazione,",
	    "	tb.data_consegna,",
	    "	tb.data_creazione,",
	    "	tb.data_modifica,",
	    "	tb.data_cancellazione,",
	    "	tb.utente_operazione,",
	    "	tb.prod_id,",
	    "	tb.prod_cod,",
	    "	tb.prod_nome,",
	    "	tb.prod_desc,",
	    "	st.id_struttura,",
	    "	st.nome",
	    "from",
	    "	(",
	    "	select",
	    "		m.magu_id,",
	    "		m.magaz_id,",
	    "		m.id_ente,",
	    "		m.quantita,",
	    "		m.data_registrazione,",
	    "		m.data_consegna,",
	    "		m.data_creazione,",
	    "		m.data_modifica,",
	    "		m.data_cancellazione,",
	    "		m.utente_operazione,",
	    "		p.prod_id,",
	    "		p.prod_cod,",
	    "		p.prod_nome,",
	    "		p.prod_desc,",
	    "		m.id_struttura",
	    "	from",
	    "		covidac_t_prod p,",
	    "		covidac_t_magaz_uscita m",
	    "	where",
	    "		p.prod_id = m.prod_id",
	    "		and p.data_cancellazione is null",
	    "		and m.data_cancellazione is null",
	    "		and m.data_consegna >= now()",
	    ") as tb",
	    "left join struttura st on",
	    "	tb.id_struttura = st.id_struttura"
			})
		@Results({
			@Result(column = "magu_id", property = "maguId", jdbcType = JdbcType.INTEGER),
			@Result(column = "magaz_id", property = "magazId", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_ente", property = "idEnte", jdbcType = JdbcType.INTEGER),
			@Result(column = "quantita", property = "quantita", jdbcType = JdbcType.INTEGER),
			@Result(column = "data_registrazione", property = "dataRegistrazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_consegna", property = "dataConsegna", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_creazione", property = "dataCreazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_modifica", property = "dataModifica", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_cancellazione", property = "dataCancellazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
		    @Result(column = "prod_id", property="prodId", jdbcType=JdbcType.INTEGER),
		    @Result(column = "prod_cod", property="prodCod", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_nome", property="prodNome", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_desc", property="prodDesc", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "nome", property="nome", jdbcType=JdbcType.VARCHAR)
		})
		List<SelectAllMagazzinoUscita> selectMagazzinoUscitaIncorso(Integer idEnte);
		
		@Select({
	    "select",
	    "	tb.magu_id,",
	    "	tb.magaz_id,",
	    "	tb.id_ente,",
	    "	tb.quantita,",
	    "	tb.data_registrazione,",
	    "	tb.data_consegna,",
	    "	tb.data_creazione,",
	    "	tb.data_modifica,",
	    "	tb.data_cancellazione,",
	    "	tb.utente_operazione,",
	    "	tb.prod_id,",
	    "	tb.prod_cod,",
	    "	tb.prod_nome,",
	    "	tb.prod_desc,",
	    "	st.id_struttura,",
	    "	st.nome",
	    "from",
	    "	(",
	    "	select",
	    "		m.magu_id,",
	    "		m.magaz_id,",
	    "		m.id_ente,",
	    "		m.quantita,",
	    "		m.data_registrazione,",
	    "		m.data_consegna,",
	    "		m.data_creazione,",
	    "		m.data_modifica,",
	    "		m.data_cancellazione,",
	    "		m.utente_operazione,",
	    "		p.prod_id,",
	    "		p.prod_cod,",
	    "		p.prod_nome,",
	    "		p.prod_desc,",
	    "		m.id_struttura",
	    "	from",
	    "		covidac_t_prod p,",
	    "		covidac_t_magaz_uscita m",
	    "	where",
	    "		p.prod_id = m.prod_id",
	    "		and p.data_cancellazione is null",
	    "		and m.data_cancellazione is null",
	    "		and m.id_ente = #{idEnte,jdbcType=INTEGER}",
	    ") as tb",
	    "left join struttura st on",
	    "	tb.id_struttura = st.id_struttura"
			})
		@Results({
			@Result(column = "magu_id", property = "maguId", jdbcType = JdbcType.INTEGER),
			@Result(column = "magaz_id", property = "magazId", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_ente", property = "idEnte", jdbcType = JdbcType.INTEGER),
			@Result(column = "quantita", property = "quantita", jdbcType = JdbcType.INTEGER),
			@Result(column = "data_registrazione", property = "dataRegistrazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_consegna", property = "dataConsegna", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_creazione", property = "dataCreazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_modifica", property = "dataModifica", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_cancellazione", property = "dataCancellazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
		    @Result(column = "prod_id", property="prodId", jdbcType=JdbcType.INTEGER),
		    @Result(column = "prod_cod", property="prodCod", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_nome", property="prodNome", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_desc", property="prodDesc", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "nome", property="nome", jdbcType=JdbcType.VARCHAR)
		})
		List<SelectAllMagazzinoUscita> selectMagazzinoUscitaEnte(Integer idEnte);
		
		@Select({
	    "select",
	    "	tb.magu_id,",
	    "	tb.magaz_id,",
	    "	tb.id_ente,",
	    "	tb.quantita,",
	    "	tb.data_registrazione,",
	    "	tb.data_consegna,",
	    "	tb.data_creazione,",
	    "	tb.data_modifica,",
	    "	tb.data_cancellazione,",
	    "	tb.utente_operazione,",
	    "	tb.prod_id,",
	    "	tb.prod_cod,",
	    "	tb.prod_nome,",
	    "	tb.prod_desc,",
	    "	st.id_struttura,",
	    "	st.nome",
	    "from",
	    "	(",
	    "	select",
	    "		m.magu_id,",
	    "		m.magaz_id,",
	    "		m.id_ente,",
	    "		m.quantita,",
	    "		m.data_registrazione,",
	    "		m.data_consegna,",
	    "		m.data_creazione,",
	    "		m.data_modifica,",
	    "		m.data_cancellazione,",
	    "		m.utente_operazione,",
	    "		p.prod_id,",
	    "		p.prod_cod,",
	    "		p.prod_nome,",
	    "		p.prod_desc,",
	    "		m.id_struttura",
	    "	from",
	    "		covidac_t_prod p,",
	    "		covidac_t_magaz_uscita m",
	    "	where",
	    "		p.prod_id = m.prod_id",
	    "		and p.data_cancellazione is null",
	    "		and m.data_cancellazione is null",
	    "		and m.data_consegna >= now()",
	    "		and m.id_ente = #{idEnte,jdbcType=INTEGER}",
	    ") as tb",
	    "left join struttura st on",
	    "	tb.id_struttura = st.id_struttura"
			})
		@Results({
			@Result(column = "magu_id", property = "maguId", jdbcType = JdbcType.INTEGER),
			@Result(column = "magaz_id", property = "magazId", jdbcType = JdbcType.INTEGER),
			@Result(column = "id_ente", property = "idEnte", jdbcType = JdbcType.INTEGER),
			@Result(column = "quantita", property = "quantita", jdbcType = JdbcType.INTEGER),
			@Result(column = "data_registrazione", property = "dataRegistrazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_consegna", property = "dataConsegna", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_creazione", property = "dataCreazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_modifica", property = "dataModifica", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_cancellazione", property = "dataCancellazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
		    @Result(column = "prod_id", property="prodId", jdbcType=JdbcType.INTEGER),
		    @Result(column = "prod_cod", property="prodCod", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "prod_nome", property="prodNome", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "id_ente", property="idEnte", jdbcType=JdbcType.INTEGER),
		    @Result(column = "prod_desc", property="prodDesc", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
		    @Result(column = "nome", property="nome", jdbcType=JdbcType.VARCHAR)
		})
		List<SelectAllMagazzinoUscita> selectMagazzinoUscitaEnteInCorso(Integer idEnte);

	
}
